language: java
jdk:
  - java8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - sellerall0401@gmail.com